package com.vartanian.secondTaskDB.entity;

import lombok.Data;
import lombok.ToString;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.Set;

/**
 * This class is an entity.
 * There is an no args constructor, getters and setters for all fields, override equals, hashcode and toString methods
 * generated by lombok.
 */
@Data
@ToString(exclude = "students")
@Entity
@DynamicInsert
@DynamicUpdate
@Table(name = "UNI_GROUP")
public class uniGroup {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false)
    private Long id;

    @Column(name = "UNI_GROUP_NUMBER", nullable = false)
    private int groupNumber;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "UNI_GROUP")
    private Set<student> students;
}